apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-ping-claim # name of the volume claim, this will be used in the deployment
  namespace: exercises
spec:
  storageClassName: standard-rwo # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
